### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by akitsen** [masonnl/backup#1]
Would be nice to have an instructions guide on how to use backup.

**Comment by masonnl** [comment]
I'm still working on the backend implementation. It's finalizing completion and I will put up a user guide when it is more fully solidified. If you want a very crude experience run `./main` from the root directory (once you've `bundle installed` of course and assuming you have Ruby 2.x.x... you also need to run `bin/setup.sh` even though the last bit errors out -- as you can see; there are still things to get done before an instruction guide can be made).

**Comment by masonnl** [comment]
The README has been updated with instructions in one of the latest commits ([c624871]). Closing.

[c624871]:https://github.com/masonnl/backup/commit/c624871da68578569e716a3c402de92af4ece86c
